version: "3.7"

services:

  webserver:
    image: nginx:alpine
    container_name: ${APP}-webserver
    working_dir: /mnt/api
    volumes:
      - "./api:/mnt/api"
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: ${APP}-php-fpm
    working_dir: /mnt/api/
    volumes:
      - ./api:/mnt/api/
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - .env:/mnt/api/.env
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    container_name: ${APP}-redis

  adminredis:
    image: erikdubbelboer/phpredisadmin
    container_name: ${APP}-admin-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=GameRedis
