
<div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">App</h2>
            </div>
            <div class="card-body">
                <p>

                    <?php foreach ($this->list as $item): ?>
                        - <?php echo $item['name']; ?><br />
                    <?php endforeach; ?>
                </p>

            </div>
        </div>
    </div>
</div>
